### ISSUE TITLE
Can't use remote combinators defined with defparsec

### ISSUE THREAD

**Issue by tmbb** [dashbitco/nimble_parsec#103]
There are two ways of defining `nimble_parsec` functions or combinators: with `defparsec` and `defcombinator`. My interpretation of the docs is that they are almost equivalent except for the fact the `defcombinator` defines only the combinator (i.e. the `fun__0/6` function) while `defparsec` defines both the combinator and the the entry point function (i.e. the `fun/1` function). However, my understanding of the implementation is that `defparsec` defunes the combinator as a private function using `defp`. This means the combiantor can't be used from other modules. Se this test case:

```elixir
defmodule NimbleParsecTest do
  use ExUnit.Case, async: true

  import NimbleParsec

  describe "parsec/1 with remote combinator" do
    defmodule Remote do
      # This line will define the parsec_remote_with_defparsec__0/6 function
      defcombinator :parsec_remote,
                    choice([
                      map(ascii_char([?a..?z]), {:to_string, []}),
                      map(ascii_char([?A..?Z]), {:to_string, []})
                    ])

      # This line won't define the parsec_remote_with_defparsec__0/6 function
      defparsec :parsec_remote_with_defparsec,
                choice([
                  map(ascii_char([?a..?z]), {:to_string, []}),
                  map(ascii_char([?A..?Z]), {:to_string, []})
                ])
    end

    defparsecp :parsec_remote_repeat, repeat(parsec({Remote, :parsec_remote}))

    defparsecp :parsec_remote_repeat_with_defparsec,
               repeat(parsec({Remote, :parsec_remote_with_defparsec}))

    # This will succeed
    test "returns ok/error with repeat" do
      assert parsec_remote_repeat("az") == {:ok, ["97", "122"], "", %{}, {1, 0}, 2}
    end

    # This will fail!
    test "returns ok/error with repeat when defined with defparsec" do
      assert parsec_remote_repeat_with_defparsec("az") == {:ok, ["97", "122"], "", %{}, {1, 0}, 2}
    end
  end
end
```

My question is: what is the actually intended behaviour? Are we supposed to be able to use combinators defined with `defparsec` from other modules?

I think that the current behaviour is wrong and we should be able to use combinators defined by `defparsec` from other modules.

*Context*: I'm asking this because I'm trying to write an EEx lexer for makeup that reuses the Elixir lexer, and I've just found out that the combintors defined there by `defparsec` can't be used from outside that module.

**Comment by josevalim** [comment]
I will investigate soon but since I have you here, could you please add a LICENSE to [makeup_demo](https://github.com/tmbb/makeup_demo) if you agree and transfer it to elixir-makeup org? :D

**Comment by josevalim** [comment]
Yes, this is intentional because most times you don't want to export the combinator. We can add an option called `export_combinator`. WDYT?

**Comment by tmbb** [comment]
> Yes, this is intentional because most times you don't want to export the combinator. We can add an option called `export_combinator`. WDYT?

Hm... I'm not such a heavy user of `nimble_parsec` that I can tell how rare it is that one wants to export the combinator. I think adding that option might be a good compromise.

This leaves us with the question on what to do with the makeup lexers; I'll add an issue there

**Comment by josevalim** [comment]
@tmbb I would go and add the `export_combinator: true` option for anything you want to be reused. I think it is a rather rare case?

**Comment by tmbb** [comment]
> @tmbb I would go and add the export_combinator: true option for anything you want to be reused. I think it is a rather rare case?

Wait, let's discuss this at the Makeup issue tracker. I'm not sure I actually need this

**Comment by tmbb** [comment]
> could you please add a LICENSE to [makeup_demo](https://github.com/tmbb/makeup_demo) if you agree and transfer it to elixir-makeup org? :D

Done. The demo now contains examples of Elixir, HTML, Erlang and C code

**Comment by josevalim** [comment]
This is in!

> Done. The demo now contains examples of Elixir, HTML, Erlang and C code

Thank you!
