### ISSUE TITLE
Add a default value to `optional` combinator

### ISSUE THREAD

**Issue by elfenlaid** [dashbitco/nimble_parsec#110]
Hello 👋  Thanks for the amazing library

It would be cool if `optional` combinator could return a default value

I've stumbled upon a small problem with `optional`. `optional` gets in a way of pattern matching the end result by shifting results elements to the right. It's especially true when you have two optionals in chain. You'll never know which one produced the result unless you tag them. 

But what if we instead extend `optional` to return a default value? Here's a small example how it could look like:

```elixir
defmodule MyParser do
  import NimbleParsec

  defparsec :hello,
    string("hello")
    |> optional(
      ignore(string(" ")) |> string("world"),
      default: nil
    )
end

dbg MyParser.hello("hello") #=> {:ok, ["hello", nil], "", %{}, {1, 0}, 5}
dbg MyParser.hello("hello world") #=> {:ok, ["hello", "world"], "", %{}, {1, 0}, 11}
```

It also could make sense to cook up a special combinator for `default: nil` values. In the following example the `maybe` combinator returns the parsed result or returns `nil` if it fails to parse anything:

```elixir
defmodule MyParser do
  import NimbleParsec

  defparsec :hello,
    string("hello")
    |> maybe(
      ignore(string(" ")) |> string("world")
    )
end

dbg MyParser.hello("hello") #=> {:ok, ["hello", nil], "", %{}, {1, 0}, 5}
dbg MyParser.hello("hello world") #=> {:ok, ["hello", "world"], "", %{}, {1, 0}, 11}
```

Technically the `maybe` combinator is close to this:

```elixir
  maybe = fn (parser) ->
    choice([
      parser,
      empty() |> replace(nil)
    ])
  end
```

**Comment by josevalim** [comment]
Yes, using choice is the way to go for both cases!

**Comment by elfenlaid** [comment]
Thanks 🙇
