### ISSUE TITLE
"Combinators are built during runtime"

### ISSUE THREAD

**Issue by Flying-Toast** [dashbitco/nimble_parsec#111]
From the docs: "[Combinators are built during runtime and compiled into multiple clauses with binary matching.](https://hexdocs.pm/nimble_parsec/NimbleParsec.html#content)"

Shouldn't this actually say "Combinators are built during *compile time*"?

**Comment by josevalim** [comment]
It *depends*. Compile-time in Elixir and runtime are the same thing, except one will write bytecode to disk and the other will no. I think it is better to say "Combinators are built programatically". :) I will update it, thanks!
