### ISSUE TITLE
NimbleParsec does not respect clauses order with OTP 26.0 (Elixir 1.14.4)

### ISSUE THREAD

**Issue by nickgnd** [dashbitco/nimble_parsec#121]
Hey 👋 
first of all, thanks for the great work, that's a real pleasure to work with `nimble_parsec` 🙇 

Today I tried to update our elixir app to use the latest version of OTP (26.0) and many of our tests started to fail.

Apparently, the behaviour of NimbleParsec changed with OTP 26.0 and it does not respect anymore the order of the clauses produced at compilation time by the parser.

Here a small script that you can use to reproduce the error:

```elixir
Mix.install([{:nimble_parsec, "~> 1.0"}])

defmodule MyParser do
  import NimbleParsec

  fn_name_parser =
    empty()
    |> choice([
      string("date_diff"),
      string("date")
    ])

  defparsec(:parse, fn_name_parser, debug: true)
end

MyParser.parse("date") |> IO.inspect(label: "PARSING DATE")

MyParser.parse("date_diff") |> IO.inspect(label: "PARSING DATE_DIFF")
```

In both cases the clauses produced by the parser are identical:

```elixir
defp parse__0(<<"date_diff", rest::binary>>, acc, stack, context, comb__line, comb__offset) do
  parse__1(rest, ["date_diff"] ++ acc, stack, context, comb__line, comb__offset + 9)
end

defp parse__0(<<"date", rest::binary>>, acc, stack, context, comb__line, comb__offset) do
  parse__1(rest, ["date"] ++ acc, stack, context, comb__line, comb__offset + 4)
end

defp parse__0(rest, _acc, _stack, context, line, offset) do
  {:error, "expected string \"date_diff\" or string \"date\"", rest, context, line, offset}
end

defp parse__1(rest, acc, _stack, context, line, offset) do
  {:ok, acc, rest, context, line, offset}
end
```

And the order of the clauses is matching the one given in the `fn_name_parser` parser.

But then, when executed with:
* erlang 26.0
* elixir 1.14.4-otp-26

❌   it is unable to parse `date_diff` as whole (see the rest "_diff"):

```elixir
PARSING DATE: {:ok, ["date"], "", %{}, {1, 0}, 4}
PARSING DATE_DIFF: {:ok, ["date"], "_diff", %{}, {1, 0}, 4}
```

While, when running it with:
* erlang 25.1.2
* elixir 1.14.2-otp-25

✅ It works as expected:

```elixir
PARSING DATE: {:ok, ["date"], "", %{}, {1, 0}, 4}
PARSING DATE_DIFF: {:ok, ["date_diff"], "", %{}, {1, 0}, 9}
```

Any idea how this is possible given that the produced clauses are identical?
I know that in OTP26 the [internal sort of the keys in a map have been changed](https://www.erlang.org/news/164#maps), but it doesn't seem related 🤔 

Thanks again for the great work, please let me know if there is anything I can do.
Cheers ✌️

**Comment by josevalim** [comment]
It is an Erlang bug. I am isolating it and I will report it upstream. :)

**Comment by josevalim** [comment]
Reported here: https://github.com/erlang/otp/issues/7259

**Comment by nickgnd** [comment]
@josevalim many many thanks for isolating and reporting it in the right repo. I wish you a great day! 🙇
