### ISSUE TITLE
Add missing git tag for 1.3.1

### ISSUE THREAD

**Issue by thomasdziedzic** [dashbitco/nimble_parsec#128]
Links are broken on https://hexdocs.pm/nimble_parsec/NimbleParsec.html#integer/2 otherwise.

For example, clicking the view source link on the above link takes me to https://github.com/dashbitco/nimble_parsec/blob/v1.3.1/lib/nimble_parsec.ex#L800 which throws a 404.

**Comment by josevalim** [comment]
Done!
