### ISSUE TITLE
What is the recommended approach to deal with case insensitivity?

### ISSUE THREAD

**Issue by Schultzer** [dashbitco/nimble_parsec#140]
Hey there, I’m building an SQL parser, and I’m wondering whats the recommended approach to deal with case insensitivity, right now I’m generating upper and lower case patterns with choice for each keyword, so I can match: `SeLeCt` but this obviously increases compilation times.

The parser will be used for syntax highlighting and potentially a Ecto SQL sigil.

**Comment by josevalim** [comment]
If you were writing by hand, you would probably do: `<<s, e, l, e, c, t>> when s in [?S, ?s] and e in [?E, ?e] and ...` so that's what you should aim. Probably by creating helpers on top of `ascii_chars` and other low-level ones.

**Comment by Schultzer** [comment]
> If you were writing by hand, you would probably do: `<<s, e, l, e, c, t>> when s in [?S, ?s] and e in [?E, ?e] and ...` so that's what you should aim. Probably by creating helpers on top of `ascii_chars` and other low-level ones.

I’m building patterns with choice and ascii_chars and then concatenating them.

Do you think I would be better off writing it by hand instead?

**Comment by josevalim** [comment]
I think the version above will be better than choice. You don't have to write by hand, you can have your own helpers to build it too.

**Comment by josevalim** [comment]
Also a dupe of https://github.com/dashbitco/nimble_parsec/issues/67 :)

**Comment by Schultzer** [comment]
Thanks, closing this as https://github.com/dashbitco/nimble_parsec/issues/67#issuecomment-580628375 is a great example that I’m going to try.

I might submit a PR to add an example to the documentation since this might not be the last time it being brought up.

**Comment by josevalim** [comment]
Great idea!
