### ISSUE TITLE
Feature: Add sized_binary(combinator, size_combinator)

### ISSUE THREAD

**Issue by josevalim** [dashbitco/nimble_parsec#30]
It reads `size_combinator` from the input and then it reads N bytes from the binary. For example:

    sized_binary(combinator, integer(min: 1))

We will also add:

    sized_binary(combinator, bytes(4))

The combinator must always return a list with one element. This means this is possible:

    sized_binary(combinator, integer(min: 1) |> ignore(string(":")))

**Comment by jeffrom** [comment]
Just curious: I've implemented something that i think achieves this, which basically does a `traverse` to get the length from the input and adds it to the context, and then a `repeat_while` to increment a counter, also in the context, and repeats `ascii_char([0..255])` until the counter has reached the input size. Would what you have in mind be more efficient than this approach?

**Comment by josevalim** [comment]
Hi @jeffrom! The idea is to do something more efficient, where we read the size and then we perform `<<x::size(y)-binary>>`.

**Comment by jeffrom** [comment]
definitely looking forward to that!

**Comment by w-sanches** [comment]
@josevalim is this still wanted and has no one working on it? I could give it a try.

**Comment by josevalim** [comment]
Still wanted, yes. :)

**Comment by josevalim** [comment]
I have just pushed the ability to return `rest` from `post_traverse` which would allow someone to implement this by hand, so this is no longer relevant. :)
