### ISSUE TITLE
Use the ?x codepoints instead of "byte n" when using ascii_chars/2

### ISSUE THREAD

**Issue by whatyouhide** [dashbitco/nimble_parsec#54]
If I use `ascii_chars([?\n])` to expect a newline and there's no newline, the error that I get is `"expected byte 10"`. I would expect the error to be something like `expected ASCII character \n` or something like that.

**Comment by josevalim** [comment]
Good find. A PR is welcome!

**Comment by whatyouhide** [comment]
I literally have no time to implement this and it seems like it's not a huge problem, so I'll let this one go (to clean up my issues a bit). Feel free to reopen if someone is ready to implement!
