### ISSUE TITLE
Feature request: easy way to match string in case insensitive fashion

### ISSUE THREAD

**Issue by princemaple** [dashbitco/nimble_parsec#67]
https://tools.ietf.org/html/rfc3501 requires a lot of case insensitive string matching for keywords like "INBOX", "ALL", "BODY", "FROM". And all strings defined in ABNF is case insensitive by default https://tools.ietf.org/html/rfc5234#page-5. Is there an easy way to do case insensitive string matching that I've been missing? If there isn't one, is it possible to add this feature?

Thanks a lot.

**Comment by josevalim** [comment]
We don't plan to provide such helper but you can implement it using something like:

    ascii_chars([?F, ?f]) |> ascii_chars([?R, ?r]) |> ... |> reduce({List, :to_string, []})

You can also create a helper that encapsulates this behaviour.

**Comment by princemaple** [comment]
Thanks Jose, knowing there isn't a way that I didn't manage to find is good enough. Cheers.
