### ISSUE TITLE
How to parse escaped string containing \" characters?

### ISSUE THREAD

**Issue by ifoo** [dashbitco/nimble_parsec#72]
I would like to parse something like the following string:

> '<foo="bar",baz="xxx">'

into the following list:
> ["foo", "bar", "baz", "xxx"]

This works fine, as long as the _"bar"_ and _"baz"_ do not contain escaped strings. The following example does not work:

> '<foo="baaa\\"rrrrr",baz="xxx\\"substring\\"xxx">'

because it contains a `\"` and my combinator is defined as `utf8_string([not: ?"], min: 1)`.

Is there a recommended way of parsing strings containing escaped characters, specifically `\"` characters?

**Comment by josevalim** [comment]
Hi @ifoo! We have limited time to provide general guidance, so please use the [ElixirForum](http://www.elixirforum.com) or StackOverflow for questions/help/feedback, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thank you!
