### ISSUE TITLE
Monadic bind

### ISSUE THREAD

**Issue by asib** [dashbitco/nimble_parsec#75]
Hi, might be boneheaded but can't see any way to do a monadic bind. I'm writing a [Bencoding](https://en.wikipedia.org/wiki/Bencode) library and e.g. for byte strings, it would be useful to parse the length and then construct a parser that only parses that number of characters.

**Comment by josevalim** [comment]
This is the same as #30. So in other words, it is not yet supported. However, if you are doing byte-level encoding, then you should look into Elixir's binary matching. It is very powerful syntax and performant abstraction. This library focuses mostly on text parsing.

**Comment by asib** [comment]
Well, #30 would provide the functionality I described above but is obviously not as powerful as a generalised bind. Do you have plans to eventually support that feature?

**Comment by josevalim** [comment]
Not planned unless someone submits a pull request.
