### ISSUE TITLE
Opaque type mismatch on `lookahead/2` since 1.2.0

### ISSUE THREAD

**Issue by ymtszw** [dashbitco/nimble_parsec#96]
* NimbleParsec 1.2.0
* Elixir 1.12.3
* Erlang 24.1.4

We have this convenient helper (for our internal PlantUML parser module):

```ex
  @doc """
  `Parser.keyword` in Elm. Looks ahead for whitespace characters.

  Does not accumulate results.
  """
  def keyword(combinator \\ empty(), binary) do
    combinator
    |> ignore(
      string(binary)
      |> lookahead(
        choice([
          ascii_char([?\t, ?\s, ?\n, ?\r]),
          eos()
        ])
      )
    )
  end
```

(just as stated, this works just like [`Parser.keyword`](https://package.elm-lang.org/packages/elm/parser/latest/Parser#keyword) in Elm's parser package.)

This helper still works, but starting from 1.2.0, it starts to show dialyzer error like so:

```
lib/plantuml_parser.ex:9:no_return
Function keyword/1 has no local return.
________________________________________________________________________________
lib/plantuml_parser.ex:9:no_return
Function keyword/2 has no local return.
________________________________________________________________________________
lib/plantuml_parser.ex:14:call_without_opaque
Function call without opaqueness type mismatch.

Call does not have expected opaque term of type NimbleParsec.t() in the 2nd position.

NimbleParsec.lookahead(NimbleParsec.t(), nonempty_maybe_improper_list())
```

From the source,

* `NimbleParsec.t` is `@opaque t :: [combinator]`
* `lookahead/2` is `@spec lookahead(t, t) :: t`
* `choice/2` is `@spec choice(t, nonempty_list(t)) :: t` (which we use with `choice/1` variant where 1st argument is substituted by `empty()`) 

so we believe they at least matches typespec-wise.

I know dialyzer error is a bit hard to reproduce and debug but if someone has a clue or two it would be great.
Perhaps it is related to recent `lookahead/2` implementation fix included in 1.2.0?

**Comment by kipcole9** [comment]
I have what I think is the same issue where calls to `repeat/1` and `choice/1` produce this dialyzer warning.

I have a minimal reproducible example in the repo https://github.com/kipcole9/nimble_dialyzer

**Comment by emilianobovetti** [comment]
I've got similar warnings, it looks like optional arguments are missing in typespecs: for example [repeat](https://github.com/dashbitco/nimble_parsec/blob/f66aa93f4100a7e749d93b61a05f5e6206dbf285/lib/nimble_parsec.ex#L1440) has the following type

```elixir
@spec repeat(t, t, opts) :: t
```

where something like

```elixir
@spec repeat(t) :: t
@spec repeat(t, opts) :: t
@spec repeat(t, t, opts) :: t
```

seems to fix the warning I'm getting.

I'm not sure why this wasn't an issue before, looking at the [diff between 1.2.0 and 1.1.0](https://github.com/dashbitco/nimble_parsec/compare/v1.1.0...v1.2.0#diff-509d8ec6f232d9f8321c76889fd3516762b4c764622c436fef61b7241517dd68) only thing I can notice is both `choice` and `repeat` got a new `opts` argument.

However adding specs like `@spec repeat(t) :: t` and `@spec choice(nonempty_list(t)) :: t` works for me. I've made this experiment [here](https://github.com/emilianobovetti/nimble_parsec/tree/add-typespecs-for-optional-args) and I'll gladly submit a pr if it helps somehow.

**Comment by josevalim** [comment]
Please do send a PR!

**Comment by ymtszw** [comment]
Thank you @emilianobovetti and @kipcole9 for patches!
Ref 84b67f204925821a02accf656fde09acd0395fa2 is dialyzer-tested against our project and the warning is resolved.
Looking for release @josevalim 👍 

/closing

**Comment by josevalim** [comment]
v1.2.1 is out!
